---
title: "R Notebook"
output: html_notebook
---

installing the package gapminder as an example of installing a package

```{r}
# load devtools
library(devtools)
install_github("jennybc/gapminder")

# successful
```
not going to do swirl since I alreeady used it during the summer internship.

```{r}
# install rafalib that is used in some data analysis later
install.packages("rafalib")
library(rafalib)
```

Demonstrate how to load a csv file:

```{r}
url <- "https://github.com/genomicsclass/dagdata/raw/master/inst/extdata/femaleMiceWeights.csv"

mouse_weights = read.csv(url)

summary(mouse_weights)
```

There a few others way to do this, including loadin local files:

```{r}
mw_path <- "./femaleMiceWeights.csv"
lmouse_weights <- read.csv(mw_path)
summary(lmouse_weights)
```

```{r}
plot(x = mouse_weights$Diet, mouse_weights$Bodyweight)
```

```{r}
plot(cars$speed, cars$dist)
car_reg_line = lm(cars$dist~cars$speed)
summary(car_reg_line)
```
```{r}
chow <- filter(lmouse_weights, Diet=="chow") # keep only the chow diet
head(chow)
```

```{r}
chowVals <- select(chow, Bodyweight)
head(chowVals)
```

```{r}
# doing them together
chowVals <- filter(lmouse_weights, Diet == 'chow') %>% select(Bodyweight)

#showing that lmuouse_weights is a data.frame
class(lmouse_weights)


#and that a subset frame of lmouse_weights is also a data.frame

class(lmouse_weights) == class(chowVals)

```
```{r}
# if we need a numeric vector:

chowVect <- filter(lmouse_weights) %>% select(Bodyweight) %>% unlist

# and the resulting object is not a data.frame
class(chowVect) != class(chowVals)
```