---
title: "Week 1 Summary"
author: Michael Penhallegon
output: 
  pdf_document: 
    highlight: zenburn
---

#A Note about course content

When going to register for the Edx program, I found out that the actual content will not re-open till Janurary 29th, however, after some web sluething, I was able to find the content from the course on [rpubs](https://rpubs.com/nishantsbi/155770). I already have both the textbook in PDF and have the datasets and sample code from the github. I should be able to complete most of the content, but will not be able to submit it to edx till the 19th.

#Introduction

This week, the course content of PH525.1x is how to install and get started in R. Since I already have done some R programming. I already have most of my enivronment setup. This was largely a review and a check to make sure that my environment was setup correctly.

# Repo setup
I have setup my work in a repo on github called (pubstatmeth)[https://github.com/howaboutudance/pubstatmeth/invitations] so I can track my progress and have my code under version control.

#Installing R

R and R-studio was already installed on my machine. I did install devtools and used the install_github to install a library from github as test case.

The course asked me to did swirl to familarize myself with R and R-studio, but again, did that this Summer.
